import {createContext, useContext, useMemo, type ReactNode} from 'react';
import {type SurgiDataMode} from '../data/repositories';
import type {CloudWorkspace} from '../data/cloud/CloudWorkspaceGate';
import type {SurgiStoreValue} from './types';
import {useSurgiStore} from './slices/useSurgiStore';
import {useLibraries} from '../core/LibraryStore';

export type {
  DeliveryPayload,
  PreparationPayload,
  ReceivePayload,
  SessionUser,
  SterilizationCompletionPayload,
  SterilizationReleasePayload,
  SurgicalCount,
  UserRole,
  WorkflowCheckpointPayload,
} from './types';
const Ctx = createContext<SurgiStoreValue | null>(null);
// eslint-disable-next-line react-refresh/only-export-components
export const useSurgi = () => {
  const x = useContext(Ctx);
  if (!x) throw new Error('useSurgi outside provider');
  return x;
};
export function SurgiProvider({
  children,
  dataMode = 'DEMO',
  cloud,
}: {
  children: ReactNode;
  dataMode?: SurgiDataMode;
  cloud?: CloudWorkspace | null;
}) {
  const {
    acknowledgeOutOfUse,
    activeDepartment,
    addAssetPhotos,
    addToolsToSet,
    applyColorPlan,
    assignDepartment,
    can,
    cloudOrganizationId,
    completeDeliveryToDepartment,
    completeSterilizationCycle,
    completeWorkflowCheckpoint,
    configureUsageLimit,
    counts,
    createProcessLoad,
    createPurchaseOrder,
    createSet,
    createTool,
    currentUser,
    deleteSet,
    deleteTool,
    deliveries,
    duplicateSet,
    duplicateTool,
    issues,
    lifecycleAlerts,
    markLost,
    moveTool,
    movements,
    nextBarcode,
    permissions,
    preparations,
    processLoads,
    purchaseOrders,
    addToBin,
    purgeExpiredBin,
    purgeFromBin,
    removeFromBin,
    recallCases,
    recallProcessLoad,
    recycleBin,
    receipts,
    receiveAtSterilization,
    receivePurchaseOrder,
    recordCount,
    forgetMovements,
    recordPreparation,
    reissueBarcode,
    releaseProcessLoad,
    finishProcessLoad,
    recordBiologicalResult,
    advanceStageItems,
    releaseSterilization,
    removeAssetPhoto,
    renameTools,
    restoreFromBin,
    replaceFromStock,
    replaceToolInSet,
    reportIssue,
    reportSetIssue,
    resolveIssues,
    retireAsset,
    returnToService,
    role,
    sessionReady,
    sessionUser,
    sendSetToService,
    sendToSterilization,
    setColorMarker,
    setPurchaseOrderStatus,
    setRole,
    setSessionUser,
    setToast,
    sets,
    sterilizationCycles,
    sterilizationReleases,
    switchIdentity,
    syncCompositionNames,
    toast,
    tools,
    undoable,
    updateSet,
    updateTool,
    workflowCheckpoints,
  } = useSurgiStore({dataMode, cloud});
  // Studio settings the actions read (workflow stages and policies, permissions): a change must reach them.
  const {sterilizationWorkflow, rolePermissions, systemSettings} = useLibraries();

  const activeTools = useMemo(() => tools.filter(t => t.state !== 'RETIRED'), [tools]);
  const retiredTools = useMemo(() => tools.filter(t => t.state === 'RETIRED'), [tools]);
  const value = useMemo(
    () => ({
      sets,
      tools: activeTools,
      retiredTools,
      movements,
      issues,
      counts,
      receipts,
      preparations,
      sterilizationCycles,
      processLoads,
      recallCases,
      sterilizationReleases,
      workflowCheckpoints,
      deliveries,
      purchaseOrders,
      recycleBin,
      restoreFromBin,
      addToBin,
      removeFromBin,
      purgeFromBin,
      purgeExpiredBin,
      replaceFromStock,
      receivePurchaseOrder,
      createPurchaseOrder,
      setPurchaseOrderStatus,
      organizationId: cloudOrganizationId,
      organizationName: cloud?.organizationName,
      lifecycleAlerts,
      toast,
      role,
      activeDepartment,
      currentUser,
      sessionReady,
      permissions,
      can,
      setRole,
      setSessionUser,
      switchIdentity,
      sendToSterilization,
      receiveAtSterilization,
      recordPreparation,
      completeSterilizationCycle,
      createProcessLoad,
      releaseProcessLoad,
      finishProcessLoad,
      recordBiologicalResult,
      advanceStageItems,
      recallProcessLoad,
      releaseSterilization,
      completeWorkflowCheckpoint,
      completeDeliveryToDepartment,
      configureUsageLimit,
      recordCount,
      forgetMovements,
      moveTool,
      replaceToolInSet,
      reportIssue,
      resolveIssues,
      addAssetPhotos,
      removeAssetPhoto,
      nextBarcode,
      createTool,
      createSet,
      reissueBarcode,
      duplicateSet,
      duplicateTool,
      deleteSet,
      deleteTool,
      acknowledgeOutOfUse,
      reportSetIssue,
      retireAsset,
      setColorMarker,
      applyColorPlan,
      markLost,
      returnToService,
      sendSetToService,
      assignDepartment,
      undoable,
      updateSet,
      updateTool,
      renameTools,
      syncCompositionNames,
      addToolsToSet,
      clearToast: () => setToast(undefined),
    }),
    // The actions are recreated every render and close over the state listed here, so keep this list in
    // sync with the state they read.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [
      sets,
      tools,
      movements,
      issues,
      counts,
      receipts,
      preparations,
      sterilizationCycles,
      processLoads,
      recallCases,
      sterilizationReleases,
      workflowCheckpoints,
      deliveries,
      purchaseOrders,
      recycleBin,
      lifecycleAlerts,
      toast,
      role,
      sessionUser,
      cloudOrganizationId,
      sterilizationWorkflow,
      rolePermissions,
      systemSettings,
    ],
  );
  return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}
