-- Speed (T4). Row-level rules called the access helpers (current_org_id(), is_platform_admin(), …)
-- once per row: reading the 13,923 instruments of a hospital spent ~15x the time on those calls.
-- Wrapped as (SELECT helper()), Postgres evaluates each once per query (an InitPlan); the rules
-- themselves are unchanged. Measured on the last page of 1,000 instruments: 333 ms -> ~22 ms.
-- Also: indexes for "what changed since" (the sync looks every few seconds on changeable tables).

alter policy trial_lock on public.asset_imports using (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked)))) with check (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked))));
alter policy deliveries_insert on public.deliveries with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('deliveries'::text))));
alter policy deliveries_read on public.deliveries using (((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));
alter policy trial_lock on public.deliveries using (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked)))) with check (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked))));
alter policy viewer_no_insert on public.deliveries with check ((NOT (SELECT is_viewer())));
alter policy dept_delete on public.departments using (((SELECT is_platform_admin()) OR ((organization_id = (SELECT current_org_id())) AND ((SELECT "current_role"()) = 'ADMIN'::surgi_role))));
alter policy dept_insert on public.departments with check (((SELECT is_platform_admin()) OR ((organization_id = (SELECT current_org_id())) AND ((SELECT "current_role"()) = 'ADMIN'::surgi_role))));
alter policy dept_read on public.departments using (((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));
alter policy dept_update on public.departments using (((SELECT is_platform_admin()) OR ((organization_id = (SELECT current_org_id())) AND ((SELECT "current_role"()) = 'ADMIN'::surgi_role)))) with check (((SELECT is_platform_admin()) OR ((organization_id = (SELECT current_org_id())) AND ((SELECT "current_role"()) = 'ADMIN'::surgi_role))));
alter policy trial_lock on public.departments using (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked)))) with check (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked))));
alter policy viewer_no_delete on public.departments using ((NOT (SELECT is_viewer())));
alter policy viewer_no_insert on public.departments with check ((NOT (SELECT is_viewer())));
alter policy viewer_no_update on public.departments using ((NOT (SELECT is_viewer())));
alter policy device_readings_insert on public.device_readings with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND ((SELECT is_cssd_operator()) OR (SELECT is_platform_admin()))));
alter policy device_readings_read on public.device_readings using (((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));
alter policy trial_lock on public.device_readings using (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked)))) with check (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked))));
alter policy viewer_no_insert on public.device_readings with check ((NOT (SELECT is_viewer())));
alter policy devices_read on public.devices using (((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));
alter policy trial_lock on public.devices using (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked)))) with check (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked))));
alter policy viewer_no_delete on public.devices using ((NOT (SELECT is_viewer())));
alter policy viewer_no_insert on public.devices with check ((NOT (SELECT is_viewer())));
alter policy viewer_no_update on public.devices using ((NOT (SELECT is_viewer())));
alter policy hospital_settings_insert on public.hospital_settings with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('library'::text))));
alter policy hospital_settings_read on public.hospital_settings using (((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));
alter policy hospital_settings_update on public.hospital_settings using ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('library'::text)))) with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('library'::text))));
alter policy trial_lock on public.hospital_settings using (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked)))) with check (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked))));
alter policy viewer_no_insert on public.hospital_settings with check ((NOT (SELECT is_viewer())));
alter policy viewer_no_update on public.hospital_settings using ((NOT (SELECT is_viewer())));
alter policy instrument_sets_delete on public.instrument_sets using ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND ((SELECT is_cssd_operator()) OR (SELECT is_platform_admin()))));
alter policy instrument_sets_insert on public.instrument_sets with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('sets'::text)) AND ((SELECT is_cssd_operator()) OR (SELECT is_platform_admin()))));
alter policy instrument_sets_read on public.instrument_sets using (((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));
alter policy instrument_sets_update on public.instrument_sets using ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('sets'::text)))) with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('sets'::text))));
alter policy trial_lock on public.instrument_sets using (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked)))) with check (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked))));
alter policy viewer_no_delete on public.instrument_sets using ((NOT (SELECT is_viewer())));
alter policy viewer_no_insert on public.instrument_sets with check ((NOT (SELECT is_viewer())));
alter policy viewer_no_update on public.instrument_sets using ((NOT (SELECT is_viewer())));
alter policy instruments_delete on public.instruments using ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND ((SELECT is_cssd_operator()) OR (SELECT is_platform_admin()))));
alter policy instruments_insert on public.instruments with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('tools'::text)) AND ((SELECT is_cssd_operator()) OR (SELECT is_platform_admin()))));
alter policy instruments_read on public.instruments using (((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));
alter policy instruments_update on public.instruments using ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('tools'::text)))) with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('tools'::text))));
alter policy trial_lock on public.instruments using (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked)))) with check (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked))));
alter policy viewer_no_delete on public.instruments using ((NOT (SELECT is_viewer())));
alter policy viewer_no_insert on public.instruments with check ((NOT (SELECT is_viewer())));
alter policy viewer_no_update on public.instruments using ((NOT (SELECT is_viewer())));
alter policy issues_delete on public.issues using ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (((SELECT "current_role"()) = 'ADMIN'::surgi_role) OR (SELECT is_platform_admin()))));
alter policy issues_insert on public.issues with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('issues'::text))));
alter policy issues_read on public.issues using (((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));
alter policy issues_update on public.issues using ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('issues'::text)))) with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('issues'::text))));
alter policy trial_lock on public.issues using (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked)))) with check (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked))));
alter policy viewer_no_delete on public.issues using ((NOT (SELECT is_viewer())));
alter policy viewer_no_insert on public.issues with check ((NOT (SELECT is_viewer())));
alter policy viewer_no_update on public.issues using ((NOT (SELECT is_viewer())));
alter policy viewer_no_delete on public.login_attempts using ((NOT (SELECT is_viewer())));
alter policy viewer_no_insert on public.login_attempts with check ((NOT (SELECT is_viewer())));
alter policy viewer_no_update on public.login_attempts using ((NOT (SELECT is_viewer())));
alter policy movements_insert on public.movements with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('movements'::text))));
alter policy movements_read on public.movements using (((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));
alter policy trial_lock on public.movements using (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked)))) with check (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked))));
alter policy viewer_no_insert on public.movements with check ((NOT (SELECT is_viewer())));
alter policy org_delete on public.organizations using ((SELECT is_platform_admin()));
alter policy org_insert on public.organizations with check ((SELECT is_platform_admin()));
alter policy org_read on public.organizations using (((id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));
alter policy org_update on public.organizations using ((SELECT is_platform_admin())) with check ((SELECT is_platform_admin()));
alter policy viewer_no_delete on public.organizations using ((NOT (SELECT is_viewer())));
alter policy viewer_no_insert on public.organizations with check ((NOT (SELECT is_viewer())));
alter policy viewer_no_update on public.organizations using ((NOT (SELECT is_viewer())));
alter policy platform_settings_update on public.platform_settings using ((SELECT is_platform_admin())) with check ((SELECT is_platform_admin()));
alter policy preparations_insert on public.preparations with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('preparations'::text))));
alter policy preparations_read on public.preparations using (((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));
alter policy trial_lock on public.preparations using (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked)))) with check (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked))));
alter policy viewer_no_insert on public.preparations with check ((NOT (SELECT is_viewer())));
alter policy process_loads_insert on public.process_loads with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('processLoads'::text))));
alter policy process_loads_read on public.process_loads using (((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));
alter policy process_loads_update on public.process_loads using ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('processLoads'::text)))) with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('processLoads'::text))));
alter policy trial_lock on public.process_loads using (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked)))) with check (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked))));
alter policy viewer_no_insert on public.process_loads with check ((NOT (SELECT is_viewer())));
alter policy viewer_no_update on public.process_loads using ((NOT (SELECT is_viewer())));
alter policy profiles_delete on public.profiles using (((SELECT is_platform_admin()) OR ((organization_id = (SELECT current_org_id())) AND ((SELECT "current_role"()) = 'ADMIN'::surgi_role) AND (id <> ( SELECT auth.uid() AS uid)))));
alter policy profiles_insert on public.profiles with check (((SELECT is_platform_admin()) OR ((organization_id = (SELECT current_org_id())) AND ((SELECT "current_role"()) = 'ADMIN'::surgi_role))));
alter policy profiles_read on public.profiles using (((id = ( SELECT auth.uid() AS uid)) OR (organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));
alter policy profiles_update on public.profiles using (((SELECT is_platform_admin()) OR ((organization_id = (SELECT current_org_id())) AND ((SELECT "current_role"()) = 'ADMIN'::surgi_role) AND (id <> ( SELECT auth.uid() AS uid))))) with check (((SELECT is_platform_admin()) OR ((organization_id = (SELECT current_org_id())) AND ((SELECT "current_role"()) = 'ADMIN'::surgi_role) AND (id <> ( SELECT auth.uid() AS uid)))));
alter policy viewer_no_delete on public.profiles using ((NOT (SELECT is_viewer())));
alter policy viewer_no_insert on public.profiles with check ((NOT (SELECT is_viewer())));
alter policy viewer_no_update on public.profiles using ((NOT (SELECT is_viewer())));
alter policy purchase_orders_insert on public.purchase_orders with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('purchaseOrders'::text))));
alter policy purchase_orders_read on public.purchase_orders using (((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));
alter policy purchase_orders_update on public.purchase_orders using ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('purchaseOrders'::text)))) with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('purchaseOrders'::text))));
alter policy trial_lock on public.purchase_orders using (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked)))) with check (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked))));
alter policy viewer_no_insert on public.purchase_orders with check ((NOT (SELECT is_viewer())));
alter policy viewer_no_update on public.purchase_orders using ((NOT (SELECT is_viewer())));
alter policy recall_cases_insert on public.recall_cases with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('recallCases'::text))));
alter policy recall_cases_read on public.recall_cases using (((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));
alter policy recall_cases_update on public.recall_cases using ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('recallCases'::text)))) with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('recallCases'::text))));
alter policy trial_lock on public.recall_cases using (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked)))) with check (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked))));
alter policy viewer_no_insert on public.recall_cases with check ((NOT (SELECT is_viewer())));
alter policy viewer_no_update on public.recall_cases using ((NOT (SELECT is_viewer())));
alter policy receipts_insert on public.receipts with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('receipts'::text))));
alter policy receipts_read on public.receipts using (((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));
alter policy trial_lock on public.receipts using (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked)))) with check (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked))));
alter policy viewer_no_insert on public.receipts with check ((NOT (SELECT is_viewer())));
alter policy recycle_bin_delete on public.recycle_bin using ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND ((SELECT is_cssd_operator()) OR (SELECT is_platform_admin()))));
alter policy recycle_bin_insert on public.recycle_bin with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('recycleBin'::text))));
alter policy recycle_bin_read on public.recycle_bin using (((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));
alter policy trial_lock on public.recycle_bin using (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked)))) with check (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked))));
alter policy viewer_no_delete on public.recycle_bin using ((NOT (SELECT is_viewer())));
alter policy viewer_no_insert on public.recycle_bin with check ((NOT (SELECT is_viewer())));
alter policy viewer_no_delete on public.signup_links using ((NOT (SELECT is_viewer())));
alter policy viewer_no_insert on public.signup_links with check ((NOT (SELECT is_viewer())));
alter policy viewer_no_update on public.signup_links using ((NOT (SELECT is_viewer())));
alter policy viewer_no_delete on public.staff_access_requests using ((NOT (SELECT is_viewer())));
alter policy viewer_no_insert on public.staff_access_requests with check ((NOT (SELECT is_viewer())));
alter policy viewer_no_update on public.staff_access_requests using ((NOT (SELECT is_viewer())));
alter policy sterilization_cycles_insert on public.sterilization_cycles with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('sterilizationCycles'::text))));
alter policy sterilization_cycles_read on public.sterilization_cycles using (((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));
alter policy trial_lock on public.sterilization_cycles using (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked)))) with check (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked))));
alter policy viewer_no_insert on public.sterilization_cycles with check ((NOT (SELECT is_viewer())));
alter policy sterilization_releases_insert on public.sterilization_releases with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('sterilizationReleases'::text))));
alter policy sterilization_releases_read on public.sterilization_releases using (((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));
alter policy trial_lock on public.sterilization_releases using (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked)))) with check (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked))));
alter policy viewer_no_insert on public.sterilization_releases with check ((NOT (SELECT is_viewer())));
alter policy surgical_counts_insert on public.surgical_counts with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('counts'::text))));
alter policy surgical_counts_read on public.surgical_counts using (((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));
alter policy trial_lock on public.surgical_counts using (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked)))) with check (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked))));
alter policy viewer_no_insert on public.surgical_counts with check ((NOT (SELECT is_viewer())));
alter policy user_invitations_admin_select on public.user_invitations using (((SELECT is_platform_admin()) OR (EXISTS ( SELECT 1 FROM profiles p WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND p.active AND (p.role = 'ADMIN'::surgi_role) AND (p.organization_id = user_invitations.organization_id))))));
alter policy viewer_no_delete on public.user_invitations using ((NOT (SELECT is_viewer())));
alter policy viewer_no_insert on public.user_invitations with check ((NOT (SELECT is_viewer())));
alter policy viewer_no_update on public.user_invitations using ((NOT (SELECT is_viewer())));
alter policy trial_lock on public.workflow_checkpoints using (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked)))) with check (((SELECT is_platform_admin()) OR (NOT ( SELECT current_org_locked() AS current_org_locked))));
alter policy viewer_no_insert on public.workflow_checkpoints with check ((NOT (SELECT is_viewer())));
alter policy workflow_checkpoints_insert on public.workflow_checkpoints with check ((((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())) AND (SELECT app_record_writable('workflowCheckpoints'::text))));
alter policy workflow_checkpoints_read on public.workflow_checkpoints using (((organization_id = (SELECT current_org_id())) OR (SELECT is_platform_admin())));

create index if not exists instrument_sets_org_updated_idx on public.instrument_sets (organization_id, updated_at);
create index if not exists instruments_org_updated_idx on public.instruments (organization_id, updated_at);
create index if not exists issues_org_updated_idx on public.issues (organization_id, updated_at);
create index if not exists process_loads_org_updated_idx on public.process_loads (organization_id, updated_at);
create index if not exists recall_cases_org_updated_idx on public.recall_cases (organization_id, updated_at);
create index if not exists purchase_orders_org_updated_idx on public.purchase_orders (organization_id, updated_at);
create index if not exists hospital_settings_org_updated_idx on public.hospital_settings (organization_id, updated_at);
